# Generated by Django 3.0.5 on 2020-06-17 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('idposts', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(200)])),
                ('post_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
    ]
