# Generated by Django 3.0.5 on 2020-06-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('idcomment', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
    ]
